apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 214813472555.dkr.ecr.us-west-2.amazonaws.com/oregon-frontend
  newName: 214813472555.dkr.ecr.us-west-2.amazonaws.com/oregon-frontend
  newTag: 61450c64
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
